Repository evrimagaci/periodum, pull requests merged in 2022-01, with the labels that each got.

#33 Update issue templates
  .github/ISSUE_TEMPLATE/bug-raporu--ablonu.md
  .github/ISSUE_TEMPLATE/hata-raporu--ablonu.md
Labels: documentation

#34 PR Şablonu ve Diğer Şablon Değişiklikleri
  .github/ISSUE_TEMPLATE/bug-raporu--ablonu.md
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: documentation

#47 'Sıcaklık Değeri Elle de Girilebilecek' #21 is solved.
  components/PeriodSelect.vue
  components/Slider.vue
  store/mutations.js
Labels: enhancement

#59 Update README.md
  README.md
Labels: documentation

#55 Blur Desteklemeyen Tarayıcılara Geçici Çözüm
  components/SideBar.vue
Labels: bug

#60 Update README.md
  README.md
Labels: documentation

#64 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#65 Update issue_template.md
  .github/ISSUE_TEMPLATE/issue_template.md
Labels: documentation

#68 Update README.md
  README.md
Labels: documentation

#69 Update FUNDING.yml
  .github/FUNDING.yml
Labels: documentation

#14 feat: selectElemet feature to right sidebar
  components/RightSideBar.vue
  pages/index.vue
Labels: enhancement
